[package]
name = "dbv-articulo"
version = "1.0.0"
entrypoint = "template/main.typ"
authors = ["David Bueno Vallejo <https://github.com/davidbuenov>"]
license = "MIT"
description = "Articulo academico corto: titulo, autoria, resumen, palabras clave y bibliografia"
categories = ["paper"]

[template]
path = "template"
entrypoint = "main.typ"
